// =====================================================
// ⚡ KIRONG AI v3
// Frontend Controller
// =====================================================

const chatBox =
  document.getElementById("chatBox");

const userInput =
  document.getElementById("userInput");

const sendBtn =
  document.getElementById("sendBtn");

const themeBtn =
  document.getElementById("themeBtn");

const thinking =
  document.getElementById("thinking");

let chatHistory = [];


// =====================================================
// 💬 ADD MESSAGE
// =====================================================

function addMessage(text, sender) {

  const message =
    document.createElement("div");

  message.className =
    `message ${sender}`;

  message.innerHTML =
    `<p>${text}</p>`;

  chatBox.appendChild(message);

  chatBox.scrollTop =
    chatBox.scrollHeight;
}


// =====================================================
// 🖼️ ADD IMAGE
// =====================================================

function addImage(image, caption = "") {

  const message =
    document.createElement("div");

  message.className =
    "message ai";

  message.innerHTML = `

    ${
      caption
        ? `<p>${caption}</p>`
        : ""
    }

    <img
      src="${image}"
      alt="Kirong AI generated image"
      style="
        display:block;
        width:100%;
        max-width:500px;
        margin-top:12px;
        border-radius:18px;
        box-shadow:0 15px 40px rgba(0,0,0,.35);
      "
    >

    <div style="
      display:flex;
      gap:10px;
      margin-top:12px;
      flex-wrap:wrap;
    ">

      <a
        href="${image}"
        download="KirongAI_Generated.png"
        style="text-decoration:none;"
      >

        <button
          style="
            padding:10px 15px;
            border:none;
            border-radius:12px;
            cursor:pointer;
          "
        >
          📥 Save Image
        </button>

      </a>

      <button
        onclick="window.open('${image}', '_blank')"
        style="
          padding:10px 15px;
          border:none;
          border-radius:12px;
          cursor:pointer;
        "
      >
        🔍 Open
      </button>

    </div>

  `;

  chatBox.appendChild(message);

  chatBox.scrollTop =
    chatBox.scrollHeight;
}


// =====================================================
// 🧠 THINKING
// =====================================================

function showThinking() {

  thinking.classList.remove(
    "hidden"
  );

}

function hideThinking() {

  thinking.classList.add(
    "hidden"
  );

}


// =====================================================
// 🚀 SEND MESSAGE
// =====================================================

async function sendMessage() {

  const text =
    userInput.value.trim();

  if (!text) return;


  // ---------------------------------------------------
  // USER MESSAGE
  // ---------------------------------------------------

  addMessage(
    text,
    "user"
  );

  userInput.value = "";

  showThinking();


  try {

    // -------------------------------------------------
    // LANGUAGE
    // -------------------------------------------------

    const languageSelect =
      document.getElementById(
        "languageSelect"
      );

    const language =
      languageSelect
        ? languageSelect.value
        : "English";


    // -------------------------------------------------
    // API REQUEST
    // -------------------------------------------------

    const response =
      await fetch(
        "/api/chat",
        {

          method: "POST",

          headers: {
            "Content-Type":
              "application/json"
          },

          body:
            JSON.stringify({

              message:
                text,

              history:
                chatHistory,

              language:
                language

            })

        }
      );


    const data =
      await response.json();


    hideThinking();


    // -------------------------------------------------
    // ERROR
    // -------------------------------------------------

    if (
      !response.ok
    ) {

      addMessage(
        data.text ||
        "⚠️ Something went wrong.",
        "ai"
      );

      return;
    }


    // -------------------------------------------------
    // 🎨 IMAGE RESPONSE
    // -------------------------------------------------

    if (
      data.type === "image" &&
      data.image
    ) {

      addImage(
        data.image,
        data.text ||
        "🎨 Image generated by Kirong AI."
      );

      return;
    }


    // -------------------------------------------------
    // 💬 TEXT RESPONSE
    // -------------------------------------------------

    addMessage(
      data.text ||
      "⚠️ Kirong AI returned no response.",
      "ai"
    );


    // -------------------------------------------------
    // HISTORY
    // -------------------------------------------------

    chatHistory.push({

      role:
        "user",

      content:
        text

    });


    chatHistory.push({

      role:
        "assistant",

      content:
        data.text || ""

    });


    // Keep history manageable

    if (
      chatHistory.length > 20
    ) {

      chatHistory =
        chatHistory.slice(-20);

    }

  }

  catch (error) {

    hideThinking();

    console.error(
      "Frontend error:",
      error
    );

    addMessage(
      "⚠️ Connection error. Please try again.",
      "ai"
    );

  }

}


// =====================================================
// 📤 SEND BUTTON
// =====================================================

sendBtn.addEventListener(
  "click",
  sendMessage
);


// =====================================================
// ⌨️ ENTER KEY
// =====================================================

userInput.addEventListener(
  "keydown",
  (event) => {

    if (
      event.key === "Enter"
    ) {

      event.preventDefault();

      sendMessage();

    }

  }
);


// =====================================================
// 🌙 THEME
// =====================================================

if (
  localStorage.getItem(
    "theme"
  ) === "dark"
) {

  document.body.classList.add(
    "dark"
  );

  themeBtn.textContent =
    "☀️";

}


themeBtn.addEventListener(
  "click",
  () => {

    document.body.classList.toggle(
      "dark"
    );

    const dark =
      document.body.classList.contains(
        "dark"
      );

    themeBtn.textContent =
      dark
        ? "☀️"
        : "🌙";

    localStorage.setItem(
      "theme",
      dark
        ? "dark"
        : "light"
    );

  }
);


// =====================================================
// ⚡ QUICK ACTIONS
// =====================================================

document
  .querySelectorAll(".quickBtn")
  .forEach((button) => {

    button.onclick =
      () => {

        const action =
          button.dataset.action;

        if (
          action === "Image"
        ) {

          userInput.value =
            "Nigeneretie picha ya ";

        }

        else {

          userInput.value =
            action + " ";

        }

        userInput.focus();

      };

  });


// =====================================================
// 🗑️ CLEAR CHAT
// =====================================================

document
  .getElementById("clearBtn")
  .onclick =
  () => {

    chatBox.innerHTML = `

      <div class="message ai">

        <p>
          Hello 👋<br>
          I am <b>Kirong AI</b>.<br>
          How can I help you today?
        </p>

      </div>

    `;

    chatHistory = [];

  };


// =====================================================
// 💾 EXPORT CHAT
// =====================================================

document
  .getElementById("exportBtn")
  .onclick =
  () => {

    const text =
      [
        ...document.querySelectorAll(
          ".message"
        )
      ]

      .map(
        (message) =>
          message.innerText
      )

      .join("\n\n");


    const blob =
      new Blob(
        [text],
        {
          type:
            "text/plain"
        }
      );


    const url =
      URL.createObjectURL(
        blob
      );


    const link =
      document.createElement(
        "a"
      );

    link.href =
      url;

    link.download =
      "KirongAI_Chat.txt";

    link.click();


    URL.revokeObjectURL(
      url
    );

  };


// =====================================================
// 📍 LOCATION
// =====================================================

document
  .getElementById("locationBtn")
  .onclick =
  () => {

    if (
      !navigator.geolocation
    ) {

      addMessage(
        "Location is not supported by this browser.",
        "ai"
      );

      return;

    }


    navigator
      .geolocation
      .getCurrentPosition(

        (position) => {

          const latitude =
            position.coords.latitude
              .toFixed(4);

          const longitude =
            position.coords.longitude
              .toFixed(4);


          addMessage(

            `📍 Latitude: ${latitude}<br>
             Longitude: ${longitude}`,

            "ai"

          );

        },

        () => {

          addMessage(
            "📍 I could not access your location.",
            "ai"
          );

        }

      );

  };


// =====================================================
// 📎 FILE UPLOAD
// =====================================================

const fileInput =
  document.getElementById(
    "fileInput"
  );


document
  .getElementById("uploadBtn")
  .onclick =
  () => {

    fileInput.click();

  };


fileInput.onchange =
  () => {

    if (
      fileInput.files.length
    ) {

      const file =
        fileInput.files[0];

      addMessage(

        `📎 ${file.name}`,

        "user"

      );

    }

  };
